
package Vista;


import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import Controlador.consulta_Proyectores_Video;
import Controlador.consulatas_Proyectores_Opacos;


public class formulario_Principal extends javax.swing.JFrame {
    fondoJpanel fondo = new fondoJpanel();
    Formulario_Proyectores fort = new Formulario_Proyectores();
    consulta_Proyectores_Video video = new consulta_Proyectores_Video();
    consulatas_Proyectores_Opacos opacos = new consulatas_Proyectores_Opacos();
    String box;

    

    /**
     * Creates new form formulario_Principal
     */
    public formulario_Principal() {
         this.setContentPane(fondo);
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Proyectores");

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jButton2.setText("Alquilar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jButton3.setText("Entregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jButton1)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(72, 72, 72)
                        .addComponent(jButton3)))
                .addGap(81, 108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Formulario_Proyectores pro = new Formulario_Proyectores();
     pro.setVisible(true);
     this.setVisible(false);
     
          box= fort.boxSeleccion.getItemAt(fort.boxSeleccion.getSelectedIndex());
        if (box.equals("Proyectores de video")) {
            fort.labelHora.setVisible(true);
            fort.labelFecha.setVisible(true);
            fort.textHora.setVisible(true);
            fort.textFecha.setVisible(true);
            fort.labelMarca.setVisible(true);
            fort.textMarca.setVisible(true);
            fort.labelMarca.setText("Ingrese el Codigo del protector de video que va a alquilar ");
            
         
            video.cargarTabla(fort.Tabla);


        } else if (box.equals("Proyectores opacos")) {
            fort.labelHora.setVisible(true);
            fort.labelFecha.setVisible(true);
            fort.textHora.setVisible(true);
            fort.textFecha.setVisible(true);
            fort.labelMarca.setVisible(true);
            fort.textMarca.setVisible(true);
            fort.labelMarca.setText("Ingrese el Codigo del protector opaco que va a alquilar ");
            
            opacos.cargarTabla(fort.Tabla);
            
        }
     

     
    fort.locassss.setText("Alquilar Proyectores");
     fort.nombrelabel.setVisible(false);
     fort.lugarLabel.setVisible(false);
     fort.RegistaradorLabel.setVisible(false);
     fort.textrRegistrador.setVisible(false);
     fort.textLugar.setVisible(false);
     fort.textNombre.setVisible(false);
     
     fort.labelColor.setVisible(false);
     fort.labelMarca.setVisible(false);
     fort.labelHora.setVisible(false);
     fort.labelFecha.setVisible(false);
             
             
     fort.textColor.setVisible(false);
     fort.textMarca.setVisible(false);
     fort.textHora.setVisible(false);
     fort.textFecha.setVisible(false);
     
        fort.buttonRegistrar.setVisible(false);
        fort.buttonBuscar.setVisible(false);
        fort.buttonEditar.setVisible(false);
        fort.buttonEliminar.setVisible(false);
        
 
     
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Formulario_Proyectores pro = new Formulario_Proyectores();
     pro.setVisible(true);
     this.setVisible(false);

     
     
         box= fort.boxSeleccion.getItemAt(fort.boxSeleccion.getSelectedIndex());
        if (box.equals("Proyectores de video")) {
            fort.labelHora.setVisible(true);
            fort.labelFecha.setVisible(true);
            fort.textHora.setVisible(true);
            fort.textFecha.setVisible(true);
            fort.labelColor.setVisible(true);
            fort.labelMarca.setVisible(true);
            fort.textColor.setVisible(true);
            fort.textMarca.setVisible(true);
            
            
         
            video.cargarTabla(fort.Tabla);


        } else if (box.equals("Proyectores opacos")) {
            fort.labelHora.setVisible(true);
            fort.labelColor.setVisible(false);
            fort.textColor.setVisible(false);
            fort.labelFecha.setVisible(true);
            fort.textHora.setVisible(true);
            fort.textFecha.setVisible(true);
            fort.labelMarca.setVisible(true);
            fort.textMarca.setVisible(true);
            fort.labelMarca.setText("Numero de Lamparas");
            
            opacos.cargarTabla(fort.Tabla);
            
        }
     
          fort.labelColor.setVisible(false);
          fort.labelMarca.setVisible(false);
          fort.labelHora.setVisible(false);
          fort.labelFecha.setVisible(false);
          fort.textColor.setVisible(false);
          fort.textMarca.setVisible(false);
          fort.textHora.setVisible(false);
          fort.textFecha.setVisible(false);
     
 
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Formulario_Proyectores pro = new Formulario_Proyectores();
        pro.setVisible(true);
        this.setVisible(false);
        
        
     box= fort.boxSeleccion.getItemAt(fort.boxSeleccion.getSelectedIndex());
        if (box.equals("Proyectores de video")) {
            fort.labelHora.setVisible(true);
            fort.labelFecha.setVisible(true);
            fort.textHora.setVisible(true);
            fort.textFecha.setVisible(true);
            fort.labelMarca.setVisible(true);
            fort.textMarca.setVisible(true);
            fort.labelMarca.setText("Ingrese el Codigo del proyector de video que va a devolver ");
            
         
            video.cargarTabla(fort.Tabla);


        } else if (box.equals("Proyectores opacos")) {
            fort.labelHora.setVisible(true);
            fort.labelFecha.setVisible(true);
            fort.textHora.setVisible(true);
            fort.textFecha.setVisible(true);
            fort.labelMarca.setVisible(true);
            fort.textMarca.setVisible(true);
            fort.labelMarca.setText("Ingrese el Codigo del protector opaco que va a devolver ");
            
            opacos.cargarTabla(fort.Tabla);
            
        } 
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
      
    fort.locassss.setText("Devolver Proyectores");
     fort.nombrelabel.setVisible(false);
     fort.lugarLabel.setVisible(false);
     fort.RegistaradorLabel.setVisible(false);
     fort.textrRegistrador.setVisible(false);
     fort.textLugar.setVisible(false);
     fort.textNombre.setVisible(false);
     
     fort.labelColor.setVisible(false);
     fort.labelMarca.setVisible(false);
     fort.labelHora.setVisible(false);
     fort.labelFecha.setVisible(false);
             
             
     fort.textColor.setVisible(false);
        fort.textMarca.setVisible(false);
        fort.textHora.setVisible(false);
        fort.textFecha.setVisible(false);

        fort.buttonRegistrar.setVisible(false);
        fort.buttonBuscar.setVisible(false);
        fort.buttonEditar.setVisible(false);
        fort.buttonEliminar.setVisible(false);

 
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    class fondoJpanel extends JPanel
    {
     private Image imagen;
     
     @Override
     public void paint(Graphics g)
     {
         imagen = new ImageIcon(getClass().getResource("/Imagenes/esta.jpg")).getImage();
         
         g.drawImage(imagen,0, 0, getWidth(), getHeight(), this);
         
         setOpaque(false);
         super.paint(g);
     }
    }




}
